### ISSUE TITLE
Add timeline with the events

### ISSUE THREAD

**Issue by guillermo-carrasco** [guillermo-carrasco/bcbio-nextgen-monitor#16]
On the top of both the table and the graph. Ask @ewels about the library used in GenStat? :stuck_out_tongue_winking_eye:

**Comment by ewels** [comment]
Hah, bad news sorry - no library used in GenStat. That's all custom code :grin:

Shout if you'd like me to cut it out for you. I don't think it's _too_ horrible..

**Comment by guillermo-carrasco** [comment]
Damn, ok, I'll ping you when I start working on this, thanks dude!

**Comment by guillermo-carrasco** [comment]
Maybe: https://jsfiddle.net/api/post/library/pure/

**Comment by ewels** [comment]
This JSFiddle link seems empty?

**Comment by guillermo-carrasco** [comment]
outch! Thanks @ewels 

https://developers.google.com/chart/interactive/docs/gallery/timeline

**Comment by guillermo-carrasco** [comment]
Or I could just use the [stacked bars](https://bootswatch.com/flatly/) from the theme and build dynamically. i.e first step finished will occupy 100%, on the second step I would calculate relative percentages, etc. Not sure how informative is that...

**Comment by ewels** [comment]
Yeah, or [stacked progress bars](http://getbootstrap.com/components/#progress-stacked)?

I'd forget about frameworks altogether to be honest (as I did with GenStat). This isn't very difficult to do in jQuery :grinning:

**Comment by guillermo-carrasco** [comment]
Yeah that's what I was talking about :-) thanks @ewels !

**Comment by ewels** [comment]
How about something custom like this? https://jsfiddle.net/sLunwg02/

Done whilst sat on a bus, so a bit messy :grin: 

Then add on [bootstrap tooltips](http://getbootstrap.com/javascript/#tooltips) to the divs to give extra information about the steps or something.

You could put a small square in the table next to each rows too, as a sort of colour key.

**Comment by guillermo-carrasco** [comment]
> Done whilst sat on a bus, so a bit messy :grin:

:unamused: come on... haha

**Comment by ewels** [comment]
It's true! ;) I'm sat on a flygbuss to Skavsta. Looks like the final `div` isn't being coloured, and I can't be bothered to figure out why ;)

**Comment by guillermo-carrasco** [comment]
Use [this](http://momentjs.com/docs/#/displaying/difference/) to calculate difference, etc
