### ISSUE TITLE
Center logo

### ISSUE THREAD

**Issue by guillermo-carrasco** [guillermo-carrasco/bcbio-nextgen-monitor#31]
Seems like the bcbio-nextgen logo is not centered within the magnifying glass.

**Comment by ewels** [comment]
![designer](https://pbs.twimg.com/media/BLdVmmeCcAAId_W.png)

**Comment by guillermo-carrasco** [comment]
haha, nice xD

**Comment by ewels** [comment]
Lush :+1:

**Comment by guillermo-carrasco** [comment]
Obviously, @robinandeer helped :) #34
