### ISSUE TITLE
Deal with analyses restarts 

### ISSUE THREAD

**Issue by guillermo-carrasco** [guillermo-carrasco/bcbio-nextgen-monitor#39]
If a user restarts a failed analyses without removing the old log file, `bcbio` will continue writing on the same log file without cleaning it. This is not a bug but a design choice, since previous run information may be useful. 

The problem though is that the monitor can't deal with this yet, and it will find "repeated" steps and mess it up. Possible solutions are:

1. When finding a stacktrace, just continue reading instead of stopping. Annotate somewhere that a stacktrace was found.
2. Implement the logic to detect this situation, by _for example_ detecting 2 "Organize samples" steps. Then show somehow to the user (create two tables/flowcharts instead of just one?)

If both scenarios the monitor needs to deal with repeated step id's. 

Thanks @lpantano and @ohofmann for pointing this out. Suggestions on how to deal with this are very much welcome :)

**Comment by guillermo-carrasco** [comment]
This seems to be a nice way:

![screen shot 2015-11-20 at 15 46 28](https://cloud.githubusercontent.com/assets/1574147/11302527/56e4aa50-8f9e-11e5-985c-57649689b1f8.png)

Just add a tab for every re-run, so that you can easily see how many re-runs there have been, where did they fail, etc.

**Comment by lpantano** [comment]
oh that's so sweet!!!!!

**Comment by guillermo-carrasco** [comment]
:smiley: glad you like it @lpantano !
