### ISSUE TITLE
Summary stats after finishing run

### ISSUE THREAD

**Issue by guillermo-carrasco** [guillermo-carrasco/bcbio-nextgen-monitor#7]
What kind of stats that could be extracted from the logs would be nice to have?

**Comment by ohofmann** [comment]
I don't think we need too much -- a lot of the report creation that comes from Lorena's and Rory's template is a bit time intensive. The first summary table comes to mind which I _think_ can be created relatively quickly.

**Comment by guillermo-carrasco** [comment]
Yes, I was thinking more on infrastructure-analysis related things, like nodes used during the analysis, time for each step, etc. I'll see :-)

**Comment by ohofmann** [comment]
We don't really have a way to measure progress through the different steps given how many environments bcbio runs on. Lemme think ;)
